### ISSUE TITLE
The solution has error.

### ISSUE THREAD

**Issue by sameer882000** [londonappbrewery/bitcoin-flutter-gold-solution#1]
Error: A value of type 'double' can't be assigned to a variable of type 'Map<String, String>'.
 - 'Map' is from 'dart:core'.
        coinValues = data;

**Comment by sbca98** [comment]
Hi @sameer882000 can you show your code? I think the solution works just fine because the double value is converted to string before assigning to the map.

**Comment by sameer882000** [comment]
> Hi @sameer882000 can you show your code? I think the solution works just fine because the double value is converted to string before assigning to the map.

Thanks. I realised my mistake.
